device: cpu
seed: 42

data:
  isthrough: false
  folder: /home/scxsz1/zsh/Learning/MARL/PSTT/data/early
  file: pu-llr-spr17.xml

method:
  name: HybridMAPPO
  epoch: 50
  reproduction: false
  discount: 0.5
  quickrun: false

config:
  technique: HybridMAPPO
  author: ZSH
  institution: UNNC
  country: China
  include_students: false
  report: false
  output: /home/scxsz1/zsh/Learning/MARL/PSTT/MARL/HybridMAPPO/results

train:
  env_name: HybridMAPPO
  device: 'cuda:1'
  discount: 0.5 # works when method.name in [CGCS,Random]
  random_warmup: 200
  warmup_episode: 250
  total_episodes: 200
  obs_shape: None
  action_dim: 10
  sched_action_dim: 10
  sched_actor_lr: 1e-4
  sched_critic_lr: 1e-3
  steps_clip: 20
  sched_hidden_dim: 512
  gamma: 0.99
  sched_gamma: 0.99
  lmbda: 0.97
  sched_lmbda: 0.97
  eps: 0.1
  sched_eps: 0.1
  sched:
    gamma: 0.95
    learning_rate: 0.7
    max_epsilon: 1.0
    min_epsilon: 0.05
    decay_rate: 0.01
  mappo:
    gamma: 0.99
    lmbda: 0.97
    eps: 0.1
    hidden_dim: 256
    actor_lr: 1e-4
    critic_lr: 1e-3
  MIP:
    max_backtracks: 60
    time_limit: 6000
    Threads: 32
    MIPGap: 0.05
    PoolSolutions: 10
  HybridMAPPO:
    path: /home/scxsz1/zsh/Learning/MARL/PSTT/MARL/HybridMAPPO/config.yaml
